# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
#update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.53.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    
    
  end

  desc "Generate IPA”
  lane :generateIPA do
    match(git_url: "https://a-rodriguez296@bitbucket.org/a-rodriguez296/promoskeys.git", 
      type: "appstore",
      app_identifier: "com.arf.Promos",
      readonly: true)
       gym(clean: true)
  end
  desc "Generate Provisioning Profiles”
  lane :generatePP do
    match(git_url: "https://a-rodriguez296@bitbucket.org/a-rodriguez296/promoskeys.git", 
      type: "development",
      app_identifier: "com.arf.Promos")
    match(git_url: "https://a-rodriguez296@bitbucket.org/a-rodriguez296/promoskeys.git", 
      type: "appstore",
      app_identifier: "com.arf.Promos")
  end

  desc "Download Provisioning Profiles”
  lane :downloadPP do
    match(git_url: "https://a-rodriguez296@bitbucket.org/a-rodriguez296/promoskeys.git", 
      type: "development",
      app_identifier: "com.arf.Promos",
      readonly: true)
    match(git_url: "https://a-rodriguez296@bitbucket.org/a-rodriguez296/promoskeys.git", 
      type: "appstore",
      app_identifier: "com.arf.Promos",
      readonly: true)
      #gym(clean: true)
  end



  =begin



  desc “Snapshots”
  lane :snapshots do
    snapshot(scheme: "PokerUITests", 
    clear_previous_screenshots: true, 
    reinstall_app: true, 
    project: "./mZone Poker.xcodeproj",
    devices: (["iPhone 4s", "iPhone 5"]),
    languages: (["en-US"]))
  end
  desc "Runs all the tests"
  lane :test do
    scan
  end
  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "mZone Poker") # Build your app - more options available
    pilot
    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end
  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "mZone Poker") # Build your app - more options available
    deliver(force: true)
    # frameit
  end



  =end




  # You can define as many lanes as you want
  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end
  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/docs/Actions.md